CREATE TABLE "TASK" 
   (
    "ID" number primary key not null,
    "VERSION" NUMBER NOT NULL ENABLE, 
    "CHECKED" VARCHAR2(2 BYTE) COLLATE "USING_NLS_COMP", 
    "DESCRIPTION" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
    "TARGET_DATE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )   ;

GRANT INSERT,UPDATE,DELETE ON TASK TO HR;

CREATE UNIQUE INDEX "TASK_C_ID_PKX" ON "TASK" ("ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;

CREATE SEQUENCE  "TASK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  